// Re-export base Item subcomponents that don't need styling changes
export {
  ItemStart,
  ItemContent,
  ItemHeader,
  ItemTitle,
  ItemActions,
  ItemFooter,
  ItemMedia,
  ItemIcon,
  ItemContext,
  useItemContext,
  itemStartVariants,
  itemContentVariants,
  itemHeaderVariants,
  itemTitleVariants,
  itemActionsVariants,
  itemFooterVariants,
  itemMediaVariants,
  itemIconVariants,
  type ItemStartProps,
  type ItemContentProps,
  type ItemHeaderProps,
  type ItemTitleProps,
  type ItemActionsProps,
  type ItemFooterProps,
  type ItemMediaProps,
  type ItemIconProps,
} from '@base-joy/ui-unstyled';

// Export styled versions
export {
  Item,
  ItemEnd,
  ItemDescription,
  styledItemVariants,
  styledItemDescriptionVariants,
  styledItemEndVariants,
  StyledItemContext,
  useStyledItemContext,
  type ItemProps,
  type ItemEndProps,
  type ItemDescriptionProps,
} from './Item';
